name: Build and Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

#  schedule:
#    - cron: "0 12 * * 2,5"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        curl -s -o vrel.txt https://api.github.com/repos/vlang/v/releases/latest
        VNAME=$(cat vrel.txt | jq -r '.name')
        VTAG=$(cat vrel.txt | jq -r '.tag_name')
        curl -s -o drel.txt https://api.github.com/repos/prantlf/docker-vlang/releases/latest
        DNAME=$(cat drel.txt | jq -r '.name')
        if [[ "$VNAME" != "$DNAME" ]]; then
          echo "publish=true" >> $GITHUB_OUTPUT
          echo "name=$VNAME" >> $GITHUB_OUTPUT
          echo "tag=$VTAG" >> $GITHUB_OUTPUT
        fi
      id: inspect
    - uses: docker/setup-qemu-action@v3
      if: ${{ steps.inspect.outputs.publish == 'true' }}
    - uses: docker/setup-buildx-action@v3
      if: ${{ steps.inspect.outputs.publish == 'true' }}
    - uses: docker/metadata-action@v5
      if: ${{ steps.inspect.outputs.publish == 'true' }}
      id: meta
      with:
        images: |
          ghcr.io/prantlf/vlang
          prantlf/vlang
        tags: |
          type=raw,value=${{ steps.inspect.outputs.name }}
          type=raw,latest
    - uses: docker/login-action@v3
      if: ${{ steps.inspect.outputs.publish == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@v3
      if: ${{ steps.inspect.outputs.publish == 'true' }}
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        docker buildx imagetools create --tag ghcr.io/prantlf/vlang:previous ghcr.io/prantlf/vlang:latest
        docker buildx imagetools create --tag prantlf/vlang:previous prantlf/vlang:latest
      if: ${{ steps.inspect.outputs.publish == 'true' }}
    - uses: docker/build-push-action@v5
      if: ${{ steps.inspect.outputs.publish == 'true' }}
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/386,linux/arm64,linux/riscv64
        build-args: |
          VTAG=${{ steps.inspect.outputs.tag }}
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit --allow-empty -m ${{ steps.inspect.outputs.name }}
        git tag ${{ steps.inspect.outputs.tag }}
        git push origin HEAD
        git push origin ${{ steps.inspect.outputs.tag }}
      if: ${{ steps.inspect.outputs.publish == 'true' }}
    - run: |
        docker pull --platform=linux/amd64 prantlf/vlang
        ID=$(docker create --platform=linux/amd64 prantlf/vlang)
        docker cp $ID:/opt/vlang v
        docker rm $ID
        zip -r9 v-linux-x64.zip v
        rm -r v
      if: ${{ steps.inspect.outputs.publish == 'true' }}
    - run: |
        docker pull --platform=linux/386 prantlf/vlang
        ID=$(docker create --platform=linux/386 prantlf/vlang)
        docker cp $ID:/opt/vlang v
        docker rm $ID
        zip -r9 v-linux-x86.zip v
        rm -r v
      if: ${{ steps.inspect.outputs.publish == 'true' }}
    - run: |
        docker pull --platform=linux/arm64 prantlf/vlang
        ID=$(docker create --platform=linux/arm64 prantlf/vlang)
        docker cp $ID:/opt/vlang v
        docker rm $ID
        zip -r9 v-linux-arm64.zip v
        rm -r v
      if: ${{ steps.inspect.outputs.publish == 'true' }}
    - run: |
        docker pull --platform=linux/riscv64 prantlf/vlang
        ID=$(docker create --platform=linux/riscv64 prantlf/vlang)
        docker cp $ID:/opt/vlang v
        docker rm $ID
        zip -r9 v-linux-riscv64.zip v
        rm -r v
      if: ${{ steps.inspect.outputs.publish == 'true' }}
    - uses: softprops/action-gh-release@v2
      if: ${{ steps.inspect.outputs.publish == 'true' }}
      with:
        name: ${{ steps.inspect.outputs.name }}
        tag_name: ${{ steps.inspect.outputs.tag }}
        make_latest: true
        files: |
          v-linux-x64.zip
          v-linux-x86.zip
          v-linux-arm64.zip
          v-linux-riscv64.zip
