name: Build and Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/setup-v-action@v2
    - run: |
        curl -s -o vrel.txt https://api.github.com/repos/vlang/v/releases/latest
        VNAME=$(cat vrel.txt | jq -r '.name')
        VTAG=$(cat vrel.txt | jq -r '.tag_name')
        curl -s -o drel.txt https://api.github.com/repos/prantlf/docker-vlang/releases/latest
        DNAME=$(cat drel.txt | jq -r '.name')
        if [[ "$VNAME" != "$DNAME" ]]; then
          echo "publish=true" >> $GITHUB_OUTPUT
          echo "name=$VNAME" >> $GITHUB_OUTPUT
          echo "tag=$VTAG" >> $GITHUB_OUTPUT
        fi
      id: inspect
    - uses: docker/metadata-action@v5
      if: ${{ steps.inspect.outputs.publish == 'true' }}
      id: meta
      with:
        images: |
          ghcr.io/prantlf/vlang
        tags: |
          type=raw,value=${{ steps.inspect.outputs.name }}
    - uses: docker/login-action@v3
      if: ${{ steps.inspect.outputs.publish == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        push: ${{ steps.inspect.outputs.publish == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VTAG=${{ steps.inspect.outputs.tag }}
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit --allow-empty -m ${{ steps.inspect.outputs.name }}
        git tag ${{ steps.inspect.outputs.tag }}
        git push origin HEAD
        git push origin ${{ steps.inspect.outputs.tag }}
    - uses: softprops/action-gh-release@v2
      if: ${{ steps.inspect.outputs.publish == 'true' }}
      with:
        name: ${{ steps.inspect.outputs.name }}
        tag_name: ${{ steps.inspect.outputs.tag }}
        make_latest: true
